//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Tbl_Adres> Tbl_Adres { get; set; }
        public DbSet<Tbl_AltKategori> Tbl_AltKategori { get; set; }
        public DbSet<Tbl_Kategori> Tbl_Kategori { get; set; }
        public DbSet<Tbl_Kullanici> Tbl_Kullanici { get; set; }
        public DbSet<Tbl_Ozellik> Tbl_Ozellik { get; set; }
        public DbSet<Tbl_Renkler> Tbl_Renkler { get; set; }
        public DbSet<Tbl_Resim> Tbl_Resim { get; set; }
        public DbSet<Tbl_Rol> Tbl_Rol { get; set; }
        public DbSet<Tbl_Siparis> Tbl_Siparis { get; set; }
        public DbSet<Tbl_SiparisDurum> Tbl_SiparisDurum { get; set; }
        public DbSet<Tbl_Urunler> Tbl_Urunler { get; set; }
        public DbSet<Tbl_Yorumlar> Tbl_Yorumlar { get; set; }
        public DbSet<Tbl_Slider> Tbl_Slider { get; set; }
    }
}
