//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ozellik
    {
        public int Ozellik_ID { get; set; }
        public string OzellikAdi { get; set; }
        public Nullable<int> u_ID { get; set; }
    }
}
