//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Urunler
    {
        public Tbl_Urunler()
        {
            this.Tbl_Resim = new HashSet<Tbl_Resim>();
            this.Tbl_Siparis = new HashSet<Tbl_Siparis>();
        }
    
        public int u_ID { get; set; }
        public string u_Adi { get; set; }
        public Nullable<int> u_Kategori_ID { get; set; }
        public Nullable<int> u_AltKategori_ID { get; set; }
        public Nullable<int> u_Renk_ID { get; set; }
        public decimal u_Fiyat { get; set; }
        public string u_Aciklama { get; set; }
        public Nullable<int> u_Yorum_ID { get; set; }
        public Nullable<int> u_Stok { get; set; }
        public Nullable<decimal> u_indirim_Fiyat { get; set; }
        public Nullable<System.DateTime> u_DT { get; set; }
        public string u_SatılanMiktar { get; set; }
        public string u_OneCikar { get; set; }
        public string u_SayfaGoruntulenme { get; set; }
        public Nullable<decimal> u_gelisFiyati { get; set; }
    
        public virtual Tbl_AltKategori Tbl_AltKategori { get; set; }
        public virtual Tbl_Kategori Tbl_Kategori { get; set; }
        public virtual Tbl_Renkler Tbl_Renkler { get; set; }
        public virtual ICollection<Tbl_Resim> Tbl_Resim { get; set; }
        public virtual ICollection<Tbl_Siparis> Tbl_Siparis { get; set; }
        public virtual Tbl_Yorumlar Tbl_Yorumlar { get; set; }
    }
}
