//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Rol
    {
        public Tbl_Rol()
        {
            this.Tbl_Kullanici = new HashSet<Tbl_Kullanici>();
        }
    
        public int rol_ID { get; set; }
        public string rolAdi { get; set; }
    
        public virtual ICollection<Tbl_Kullanici> Tbl_Kullanici { get; set; }
    }
}
