//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Slider
    {
        public int s_ID { get; set; }
        public string SliderAdi { get; set; }
        public string SliderURL { get; set; }
        public string SliderDetay { get; set; }
        public string SliderFiyat { get; set; }
        public string Slider_indirimFiyat { get; set; }
        public string SliderKategori { get; set; }
    }
}
