//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Kullanici
    {
        public Tbl_Kullanici()
        {
            this.Tbl_Adres = new HashSet<Tbl_Adres>();
            this.Tbl_Siparis = new HashSet<Tbl_Siparis>();
        }
    
        public int kullanici_ID { get; set; }
        public string Ad { get; set; }
        public string SoyAd { get; set; }
        public string TC { get; set; }
        public string GSM { get; set; }
        public Nullable<System.DateTime> dTarihi { get; set; }
        public string Kullanici_Adi { get; set; }
        public string Sifre { get; set; }
        public string Cinsiyet { get; set; }
        public string Mail { get; set; }
        public Nullable<int> rol_ID { get; set; }
    
        public virtual ICollection<Tbl_Adres> Tbl_Adres { get; set; }
        public virtual Tbl_Rol Tbl_Rol { get; set; }
        public virtual ICollection<Tbl_Siparis> Tbl_Siparis { get; set; }
    }
}
