//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Resim
    {
        public int Resim_ID { get; set; }
        public string ResimURL { get; set; }
        public Nullable<int> urun_ID { get; set; }
    
        public virtual Tbl_Urunler Tbl_Urunler { get; set; }
    }
}
