//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Yorumlar
    {
        public Tbl_Yorumlar()
        {
            this.Tbl_Urunler = new HashSet<Tbl_Urunler>();
        }
    
        public int Yorum_ID { get; set; }
        public string Yorum_baslik { get; set; }
        public string Yorum_Detay { get; set; }
        public Nullable<int> y_Kullanici_ID { get; set; }
        public Nullable<int> Yorum_Puan { get; set; }
        public Nullable<System.DateTime> Yorum_DT { get; set; }
        public Nullable<int> y_Urun_ID { get; set; }
    
        public virtual ICollection<Tbl_Urunler> Tbl_Urunler { get; set; }
    }
}
