//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Siparis
    {
        public Tbl_Siparis()
        {
            this.Tbl_SiparisDurum = new HashSet<Tbl_SiparisDurum>();
        }
    
        public int siparis_ID { get; set; }
        public Nullable<int> urun_ID { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<System.DateTime> s_DT { get; set; }
        public Nullable<int> siparis_Durum_ID { get; set; }
        public Nullable<int> m_ID { get; set; }
        public string Adres_ID { get; set; }
    
        public virtual Tbl_Kullanici Tbl_Kullanici { get; set; }
        public virtual Tbl_Urunler Tbl_Urunler { get; set; }
        public virtual ICollection<Tbl_SiparisDurum> Tbl_SiparisDurum { get; set; }
    }
}
